"""Pydantic schemas for request and response validation."""

from app.schemas.auth import (
    LoginRequest,
    RegisterRequest,
    TokenResponse,
    UserResponse,
)
from app.schemas.common import (
    ChapterBase,
    ChapterRead,
    ExamBase,
    ExamRead,
    QuestionBase,
    QuestionOptionBase,
    QuestionOptionRead,
    QuestionRead,
    SubjectBase,
    SubjectRead,
    TestAttemptBase,
    TestAttemptRead,
    UserBase,
    UserRead,
)
from app.schemas.questions import (
    ImportIssue,
    QuestionImportSummary,
    QuestionListResponse,
    QuestionManagementRead,
    QuestionOptionInput,
    QuestionStatusUpdate,
    QuestionUpdate,
)

__all__ = [
    "RegisterRequest",
    "LoginRequest",
    "UserResponse",
    "TokenResponse",
    "UserBase",
    "UserRead",
    "ExamBase",
    "ExamRead",
    "SubjectBase",
    "SubjectRead",
    "ChapterBase",
    "ChapterRead",
    "QuestionOptionBase",
    "QuestionOptionRead",
    "QuestionBase",
    "QuestionRead",
    "TestAttemptBase",
    "TestAttemptRead",
    "ImportIssue",
    "QuestionImportSummary",
    "QuestionListResponse",
    "QuestionManagementRead",
    "QuestionOptionInput",
    "QuestionStatusUpdate",
    "QuestionUpdate",
]
